chore: add codemod util to @compiled/eslint-plugin
atlassian-labs/compiled pull request #1199
Opened 2022-04-21 06:13 UTC by DarkPurple141

Hi folks! 👋 

I'm just cleaning up the old eslint rules / utils and replacing them with an alternative library I'm trying consolidate / develop to aid these sorts of rules in future.

Let me know if any objections!

2022-04-26 00:22 UTC, JakeLane requested changes
Thanks for the contribution! 💯 

For the library, what's the plan for support and maintenance? My main concern is if we need to contribute changes upstream or any vulnerabilities that come up.

2022-04-26 00:22 UTC, JakeLane commented on packages/eslint-plugin/src/rules/jsx-pragma/index.ts
> +          // @ts-ignore
Is this required?

2022-04-26 00:22 UTC, JakeLane commented on yarn.lock
> +  resolved "https://packages.atlassian.com/api/npm/npm-remote/@babel/core/-/core-7.12.9.tgz#fd450c4ec10cdbb980e2928b7aa7a28484593fc8"
Please change this to the `yarnpkg.com` registry

2022-04-26 07:39 UTC, DarkPurple141 commented on packages/eslint-plugin/src/rules/no-emotion-css/index.ts
> +        if (node.specifiers[0] && isNodeOfType(node.specifiers[0], 'ImportNamespaceSpecifier')) {
address

2023-10-22 22:19 UTC, itsdouges commented
Closing as stale.

2023-10-22 22:19 UTC, closed without merging